project_name: go-typer

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64 # Renamed to x86_64 in outputs
      - arm64
      - "386"
    main: ./main.go
    binary: "go-typer-{{ .Version }}-{{ replace .Os `darwin` `macOS` }}-{{ if eq .Os `darwin` }}{{ if eq .Arch `arm64` }}apple-silicon{{ else }}intel{{ end }}{{ else }}{{ replace (replace .Arch `amd64` `x86_64`) `386` `i386` }}{{ end }}"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    ignore:
      - goos: darwin
        goarch: "386"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ replace .Os `darwin` `macOS` }}_{{ if eq .Os `darwin` }}{{ if eq .Arch `arm64` }}apple-silicon{{ else }}intel{{ end }}{{ else }}{{ replace (replace .Arch `amd64` `x86_64`) `386` `i386` }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

nfpms:
  - vendor: "go-typer"
    homepage: "https://github.com/prime-run/go-typer"
    maintainer: "prime-run"
    description: "go-typer: A typing game in terminal built in go"
    license: "MIT"
    formats:
      - deb
      - rpm
    bindir: /usr/bin

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: prime-run
    name: go-typer
  prerelease: auto
  draft: false
